export const paths = {
  home: '/',
  login: '/login',
  register: '/register',
  listings: '/listings',
  saved: '/saved',
  connections: '/connections',
  connectionsReceived: '/connections/received',
  connectionsSent: '/connections/sent',
  connection: (id: number) => `/connections/${id}`,
  messages: '/messages',
  conversation: (id: number) => `/messages/${id}`,
  conversationForConnection: (connectionId: number) => `/messages/connection/${connectionId}`,
  listing: (slug: string) => `/listings/${encodeURIComponent(slug)}`,
  myListings: '/my-listings',
  newListing: '/my-listings/new',
  myListing: (id: number) => `/my-listings/${id}`,
  editListing: (id: number) => `/my-listings/${id}/edit`,
  profile: '/profile',
  user: (username: string) => `/users/${encodeURIComponent(username)}`,
  admin: '/admin',
  adminReports: '/admin/reports',
  adminReport: (id: number) => `/admin/reports/${id}`,
} as const
